name: "Run AI code reviews"

on: push

jobs:
  create-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gitpython openai

      - name: Fetch Python script
        run: curl -o create_readme.py https://raw.githubusercontent.com/stancsz/auto-reviewer/main/create_review.py

      - name: Run Python script
        run: python create_readme.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
