name: Use Reusable Workflow

on:
  push:
    branches:
      - master
      - main

jobs:
  call-reusable-workflow:
    uses: stancsz/auto-reviewer/.github/workflows/create_readme_reusable.yml@main
